import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'

export default function Home () {
  return (
    <>
      <Head>
        <title>Cafetería Baratto</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Image
          src='/home-image.jpg'
          alt='image from sideview of Cafeteria Baratto'
          width={1080}
          height={600}
        />
        <title>Seccion</title>
        <subtittle> subtitulo </subtittle>
      </main>
    </>
  )
}
